---
title: "Untitled"
output: html_document
---

```{r Pseudo-Facebook User Data}
getwd()
list.files()
pf <- read.csv('pseudo_facebook.tsv', sep='\t')
names(pf)
```

```{r Histogram of Users Birthdays}
install.packages("ggplot2")
install.packages("gplot")
library(ggplot2)
names(pf)
qplot(x=dob_day, data=pf)+
  scale_x_continuous(breaks = 1:31)+
  facet_wrap(~dob_month, ncol = 3)
```
```{r Be Skeptical Outliers and Anomalies}
qplot(x = friend_count, data = pf)
qplot(x = friend_count, data = pf, xlim = c(0,1000))
qplot(x = friend_count, data = pf)+scale_x_continuous(limits = c(0, 1000))
```
```{r Adjusting the Bin Width}
qplot(x = friend_count, data = pf, binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))
```
```{r Omitting NA Observations}
qplot(x = friend_count, data = subset(pf,!is.na(gender)), binwidth = 10) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))+
  facet_wrap(~gender)

qplot(x = friend_count, data = na.omit(pf), binwidth = 10) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))+
  facet_wrap(~gender)
```
```{r Statistics by Gender}
table(pf$gender)
by(pf$friend_count, pf$gender, summary)
```
```{r Tenure, Labeling Plots}
qplot(x=tenure/365, data=pf,
  xlab='Number of years using Facebook',
  ylab='Number of users in sample',
  color=I('black'), fill=I('#099DD9'))

scale_x_continuous(breaks = seq(1, 7, 1), limits = c(0, 7))
```
```{r  Transforming Data}
qplot(x = friend_count, data=pf)
summary(pf$friend_count)
summary(log10(pf$friend_count+1))
summary(sqrt(pf$friend_count))
```
```{r Add a Scaling Layer}
install.packages('gridExtra')
library(gridExtra)
logScale <- qplot(x=log10(friend_count), data=pf)
logScale
countScale <- ggplot(aes(x = friend_count), data = pf) +
  geom_histogram()+
  scale_x_log10()
countScale
grid.arrange(logScale, countScale, ncol=2)+
  qplot(x=friend_count, data=pf)
 scale_x_log10()
```

```{r  Frequency Polygons}
qplot(x=friend_count, data=subset(pf, !is.na(gender)),
binwidth=10)+
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))+
  facet_wrap(~gender)


qplot(x=friend_count, y=..count../sum(..count..),
      data=subset(pf, !is.na(gender)),
      binwidth=10, geom='freqpoly', color=gender)+
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))
 
qplot(x=friend_count, data=subset(pf, !is.na(gender)),
      xlab='Friend Count',
      ylab='Proportion of users with that friend count',
      binwidth=10, geom='freqpoly', color=gender)+
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))
 
```
```{r Box Plots Histograms}
qplot(x=friend_count, data=subset(pf, !is.na(gender)),
binwidth=25)+
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))+
  facet_wrap(~gender)
```
```{r Box Plots }
qplot(x=gender, y=friend_count, data=subset(pf, !is.na(gender)),
geom='boxplot')
```
```{r Box Plots }
qplot(x=gender, y=friend_count, data=subset(pf, !is.na(gender)),
geom='boxplot')
coord_cartesian(ylim=c(0,250))
by(pf$friend_count, pf$gender, summary)
```
```{r Getting Logical }
summary(pf$mobile_likes)
summary(pf$mobile_likes>0)
mobile_check_in <- NA
pf$mobile_check_in <- ifelse(pf$mobile_likes>0,1,0)
pf$mobile_check_in <- factor(pf$mobile_check_in)
summary(pf$mobile_check_in)
```